# Generated by Django 4.0.3 on 2022-05-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateField(auto_now=True, verbose_name='modificado em')),
                ('imagem', models.ImageField(upload_to='', verbose_name='imagem')),
                ('descricao', models.CharField(max_length=100, null=True, verbose_name='descrição')),
                ('modelo', models.CharField(max_length=100, null=True, verbose_name='modelo')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
