# Generated by Django 4.0.3 on 2022-05-07 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateField(auto_now=True, verbose_name='modificado em')),
                ('data', models.DateField(default=None, verbose_name='data')),
                ('h_inicio', models.TimeField(verbose_name='hora inicio')),
                ('h_final', models.TimeField(verbose_name='hora final')),
                ('horas_trabalhadas', models.TimeField(verbose_name='horas trabalhadas')),
                ('maior_velocidade', models.FloatField(verbose_name='maior velocidade')),
                ('velocidade_media', models.FloatField(verbose_name='velocidade media')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Posicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateField(auto_now=True, verbose_name='modificado em')),
                ('data_hora', models.DateTimeField(verbose_name='data/hora')),
                ('lat', models.FloatField(verbose_name='latitude')),
                ('lng', models.FloatField(verbose_name='longitude')),
                ('pressao_a', models.FloatField(verbose_name='pressao a')),
                ('pressao_b', models.FloatField(verbose_name='pressao b')),
                ('fluxo_a', models.FloatField(verbose_name='fluxo a')),
                ('fluxo_b', models.FloatField(verbose_name='fluxo b')),
                ('razao', models.IntegerField(verbose_name='razao')),
                ('sentido', models.FloatField(verbose_name='sentido')),
                ('velocidade', models.FloatField(verbose_name='velocidade')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dispositivo.dispositivo')),
                ('trabalho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trabalho.trabalho')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
