# Generated by Django 4.0.3 on 2022-05-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateField(auto_now=True, verbose_name='modificado em')),
                ('img', models.ImageField(upload_to='', verbose_name='img')),
                ('nome', models.CharField(default='', max_length=20, verbose_name='nome')),
                ('north', models.FloatField(verbose_name='north')),
                ('south', models.FloatField(verbose_name='south')),
                ('east', models.FloatField(verbose_name='east')),
                ('west', models.FloatField(verbose_name='west')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
