# Generated by Django 4.0.3 on 2022-05-07 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateField(auto_now=True, verbose_name='modificado em')),
                ('modelo', models.CharField(default='', max_length=60, verbose_name='modelo')),
                ('mac', models.CharField(default='', max_length=17, verbose_name='mac')),
                ('trator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trator.trator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateField(auto_now=True, verbose_name='modificado em')),
                ('temperatura', models.FloatField(default=None, verbose_name='temperatura')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dispositivo.dispositivo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
